### ISSUE TITLE
Dulwich module not correctly installing?

### ISSUE THREAD

**Issue by KevinBollengier** [arthaud/git-dumper#2]
Anyone else having problems with installing git-dumper using pip?

For some reason Dulwich isn't installing correctly during the pip setup..

**Comment by KevinBollengier** [comment]
Hey I think I found what went wrong, some of the dependencies required (e.g: urllib 3) are not automatically up to date to use for the Dulwich module.

I did:
pip install --upgrade requests
pip install --upgrade urllib3

Now I got it working.

**Comment by KevinBollengier** [comment]
(Platform is Windows 10 btw)

**Comment by pravesh98** [comment]
I have installed python 3.7.3
but still facing ModuleNotFoundError
