### ISSUE TITLE
Use git fsck to find missing files

### ISSUE THREAD

**Issue by arthaud** [arthaud/git-dumper#3]
The tool could be improved by running `git fsck` at the end to find missing files.

**Comment by gnjax** [comment]
> 
> 
> The tool could be improved by running `git fsck` at the end to find missing files.

Could you elaborate ? Running this command will outputs missing files hashes, but I believe they are mostly contained within packed objects that weren't found by the py script

**Comment by arthaud** [comment]
That was just a thought, I didn't take the time to dig into it.
You are probably right, that won't help find missing packed objects.

**Comment by arthaud** [comment]
As discussed, that most likely won't help. Closing.
