### ISSUE TITLE
Authorization header ?

### ISSUE THREAD

**Issue by NathanSaucet** [arthaud/git-dumper#34]
Hi ! I was wondering if it were possible to add a specific header for crendentials ?
Like "Authorization: Basic myt54rdvu4f8pe1"

**Comment by arthaud** [comment]
This can already be done using `--header` or `-H`.
For instance:
```
git-dumper --header="Authorization=Basic myt54rdvu4f8pe1" URL DIR
```

**Comment by NathanSaucet** [comment]
Oh thanks ! I didn't knew that :D
