### ISSUE TITLE
Recursive download incorrectly includes ../

### ISSUE THREAD

**Issue by Reelix** [arthaud/git-dumper#9]
If http://site.com/.git/ returns a 200 response code indicating a directory listing, the script starts downloading recursively.

Unfortunately, the recursive download parses ../ which leads to is_html assertion errors (http://site.com/.git/../ goes to http://site.com/) and infinite loops (Since it returns back to a directory that it's already been through)

**Comment by hilarex** [comment]
I found a solution : just add 
`url.path != '../' and` 
on line 46

**Comment by iNoSec2** [comment]
thanks hilarex!!!  solved my problem too :)

**Comment by arthaud** [comment]
Feel free to submit a PR :)

**Comment by iNoSec2** [comment]
i made it on GitTools repo and added a` cd to BASEDIR && git checkout .` too
